disabled_rules:
  - trailing_whitespace
  - force_try

line_length: 150

cyclomatic_complexity: 12

identifier_name:
  excluded:
    - id

excluded:
  - Specs
  - IntegrationSpecs
  - PerformanceTests
  - Pods
